version: "3"

name: strapi
services:
  postgres:
    extends:
      file: strapi/docker-compose-postgres.yml
      service: postgres
    networks:
      - strapi

  adminer:
    extends:
      file: strapi/docker-compose-postgres.yml
      service: adminer
    networks:
      - strapi
    depends_on:
      - postgres

volumes:
  strapi_data:

networks:
  strapi:
    name: Strapi
    driver: bridge
