version: "3"

name: strapi
services:
  postgres:
    extends:
      file: docker-compose-postgres.yml
      service: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - 5432:5432
    networks:
      - strapi

  adminer:
    extends:
      file: docker-compose-postgres.yml
      service: adminer
    networks:
      - strapi
    depends_on:
      - postgres

volumes:
  strapi_data:

networks:
  strapi:
    name: Strapi
    driver: bridge
